name: allweather
description: A complete Flutter weather app with search, current location, hourly forecast, theme toggle, and C/F toggle using OpenWeatherMap.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  geolocator: ^13.0.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  geolocator_android: 4.6.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
